- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.1
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
      args:
        - --maxkb=128
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: double-quote-string-fixer
    - id: check-xml
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: flake8
      exclude: migrations/|admin.py|tests.py
    - id: name-tests-test
      args:
        - --django
- repo: git://github.com/Lucas-C/pre-commit-hooks.git
  sha: v1.0.1
  hooks:
    - id: forbid-crlf
- repo: git://github.com/trbs/pre-commit-hooks-trbs.git
  sha: e233916fb2b4b9019b4a3cc0497994c7926fe36b
  hooks:
    - id: forbid-executables
      exclude: manage.py|setup.py
- repo: git://github.com/jumanjihouse/pre-commit-hooks
  sha: 1.11.2
  hooks:
    - id: forbid-binary
      exclude: .png
